[package]
name = "scones-ie"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum ="0.7.2"
tokio = { version = "1.0", features = ["full"] }
