#!/bin/bash

fly secrets set GITHUB_CLIENT_SECRET="${SCONES_TEST_CLIENT_SECRET}"
fly secrets set GITHUB_CLIENT_ID=Iv1.f25c6ba01a2d8a33

fly secrets set CONNECTION_STRING="${SCONES_FLY_CONNECTION_STRING}"

export CONNECTION_STRING="${SCONES_FLY_CONNECTION_STRING}"
