name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy to fly.io
      uses: superfly/flyctl-actions@v1
      with:
        api_token: ${{ secrets.FLY_API_TOKEN }}
        app_name: scones

